/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package currency;

/**
 *
 * @author harry sahani
 */
public class Converter extends javax.swing.JFrame {
    
    
    String[] currencyunits = {
        
        " Brazilian real","Canadian dollar","Indian rupee","Indonesian Rupiah",
        "The naira","United States dollar","Kenyan Shilling"," Pakistani Rupee",
        "Australian dollar","the euro"
        
    };

    /**
     * Creates new form Converter
     */
    public Converter() {
        setBounds(300,100,800,800);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 255));

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 51, 51));
        jLabel1.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        jLabel1.setText("                                       Currency Converter");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 50));

        jLabel2.setFont(new java.awt.Font("Lucida Bright", 1, 10)); // NOI18N
        jLabel2.setText("To Currency of");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 130, 20));

        jComboBox1.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Brazil", "Canada", "India", "Indonesia", "Nigeria", "USA", "Kenya", "Pakistan", "Australia", "France" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 180, 30));

        jLabel3.setFont(new java.awt.Font("Lucida Bright", 1, 10)); // NOI18N
        jLabel3.setText("From Currency of");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 130, 20));

        jComboBox2.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Brazil", "Canada", "India", "Indonesia", "Nigeria", "USA", "Kenya", "Pakistan", "Australia", "France" }));
        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, 180, 30));

        jTextField1.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 180, -1));

        jTextField2.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, 180, -1));

        jButton1.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        jButton1.setText("Convert");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 100, 30));

        jButton2.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        jButton2.setText("Reset");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 100, 30));

        jButton3.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        jButton3.setText("Exit");
        jButton3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 70, 30));

        jLabel4.setFont(new java.awt.Font("Lucida Bright", 1, 10)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Brazilian real");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 180, -1));

        jLabel5.setFont(new java.awt.Font("Lucida Bright", 1, 10)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Brazilian real");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 180, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 677, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
jTextField1.setText("");   
jTextField2.setText(""); 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
          int position = jComboBox1.getSelectedIndex();
          jLabel4.setText(currencyunits[position]);
        
        
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged
        int position = jComboBox2.getSelectedIndex();
          jLabel5.setText(currencyunits[position]);
    }//GEN-LAST:event_jComboBox2ItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String b1 = (String)jComboBox1.getSelectedItem();
       String b2 = (String)jComboBox2.getSelectedItem();
       
       if(b1.equals("Brazil") && b2.equals("Brazil")){
           double c = Double.parseDouble(jTextField1.getText());
           jTextField2.setText(String.valueOf(c));
           
       }
       
       if(b1.equals("Brazil") && b2.equals("Canada")){
           double c = Double.parseDouble(jTextField1.getText());
           
           double k = (double)(c*0.28);
           jTextField2.setText(String.valueOf(k));
           
       }
       if(b1.equals("Brazil") && b2.equals("India")){
           double c = Double.parseDouble(jTextField1.getText());
           double k = (double)(c*16.9678);
           jTextField2.setText(String.valueOf(k));
           
       }
        if(b1.equals("Brazil") && b2.equals("Indonesia")){
           double c = Double.parseDouble(jTextField1.getText());
           double k = (double)(c*3125.96);
           jTextField2.setText(String.valueOf(k));
           
       }
         if(b1.equals("Brazil") && b2.equals("Nigeria")){
           double c = Double.parseDouble(jTextField1.getText());
           double k = (double)(c*158.036);
           jTextField2.setText(String.valueOf(k));
           
       }
          if(b1.equals("Brazil") && b2.equals("USA")){
           double c = Double.parseDouble(jTextField1.getText());
           double k = (double)(c*0.20531);
           jTextField2.setText(String.valueOf(k));   
       }
           if(b1.equals("Brazil") && b2.equals("Kenya")){
           double c = Double.parseDouble(jTextField1.getText());
           double k = (double)(c*29.6071);
           jTextField2.setText(String.valueOf(k));
       }
           if(b1.equals("Brazil") && b2.equals("Pakistan")){
           double c = Double.parseDouble(jTextField1.getText());
           double k = (double)(c*62.2217);
           jTextField2.setText(String.valueOf(k));
       }
           if(b1.equals("Brazil") && b2.equals("Australia")){
           double c = Double.parseDouble(jTextField1.getText());
           double k = (double)(c*0.31827);
           jTextField2.setText(String.valueOf(k));
       }
           if(b1.equals("Brazil") && b2.equals("France")){
           double c = Double.parseDouble(jTextField1.getText());
           double k = (double)(c*0.18941);
           jTextField2.setText(String.valueOf(k));
       }
           
//        *****Canada***   
           
           if(b1.equals("Canada") && b2.equals("Brazil")){
           double c = Double.parseDouble(jTextField1.getText());
           double k = (double)(c*0.28);
           jTextField2.setText(String.valueOf(k));
           
       }
       
       if(b1.equals("Canada") && b2.equals("Canada")){
           double c = Double.parseDouble(jTextField1.getText());
           jTextField2.setText(String.valueOf(c));
           
       }
       if(b1.equals("Canada") && b2.equals("India")){
           double c = Double.parseDouble(jTextField1.getText());
           double k = (double)(c*60.8066);
           jTextField2.setText(String.valueOf(k));
           
       }
        if(b1.equals("Canada") && b2.equals("Indonesia")){
           double c = Double.parseDouble(jTextField1.getText());
           double k = (double)(c*11202.3);
           jTextField2.setText(String.valueOf(k));
           
       }
         if(b1.equals("Canada") && b2.equals("Nigeria")){
           double c = Double.parseDouble(jTextField1.getText());
           double k = (double)(c*566.343);
           jTextField2.setText(String.valueOf(k));
           
       }
          if(b1.equals("Canada") && b2.equals("USA")){
           double c = Double.parseDouble(jTextField1.getText());
           double k = (double)(c*0.73574);
           jTextField2.setText(String.valueOf(k));   
       }
           if(b1.equals("Canada") && b2.equals("Kenya")){
           double c = Double.parseDouble(jTextField1.getText());
           double k = (double)(c*106.101);
           jTextField2.setText(String.valueOf(k));
       }
           if(b1.equals("Canada") && b2.equals("Pakistan")){
           double c = Double.parseDouble(jTextField1.getText());
           double k = (double)(c*222.98);
           jTextField2.setText(String.valueOf(k));
       }
           if(b1.equals("Canada") && b2.equals("Australia")){
           double c = Double.parseDouble(jTextField1.getText());
           double k = (double)(c*1.14055);
           jTextField2.setText(String.valueOf(k));
       }
           if(b1.equals("Canada") && b2.equals("France")){
           double c = Double.parseDouble(jTextField1.getText());
           double k = (double)(c*0.67877);
           jTextField2.setText(String.valueOf(k));
       }
           
           
         //        *****India***   
           
           if(b1.equals("India") && b2.equals("Brazil")){
           double c = Double.parseDouble(jTextField1.getText());
           double k = (double)(c*0.05889);
           jTextField2.setText(String.valueOf(k));
           
       }
       
       if(b1.equals("India") && b2.equals("Canada")){
           double c = Double.parseDouble(jTextField1.getText());
           double k = (double)(c*0.01644);
           jTextField2.setText(String.valueOf(k));
           
       }
       if(b1.equals("India") && b2.equals("India")){
           double c = Double.parseDouble(jTextField1.getText());
           jTextField2.setText(String.valueOf(c));
           
       }
        if(b1.equals("India") && b2.equals("Indonesia")){
           double c = Double.parseDouble(jTextField1.getText());
           double k = (double)(c*182.213);
           jTextField2.setText(String.valueOf(k));
           
       }
         if(b1.equals("India") && b2.equals("Nigeria")){
           double c = Double.parseDouble(jTextField1.getText());
           double k = (double)(c*9.31306);
           jTextField2.setText(String.valueOf(k));
           
       }
          if(b1.equals("India") && b2.equals("USA")){
           double c = Double.parseDouble(jTextField1.getText());
           double k = (double)(c*0.0121);
           jTextField2.setText(String.valueOf(k));   
       }
           if(b1.equals("India") && b2.equals("Kenya")){
           double c = Double.parseDouble(jTextField1.getText());
           double k = (double)(c*1.74475);
           jTextField2.setText(String.valueOf(k));
       }
           if(b1.equals("India") && b2.equals("Pakistan")){
           double c = Double.parseDouble(jTextField1.getText());
           double k = (double)(c*3.66673);
           jTextField2.setText(String.valueOf(k));
       }
           if(b1.equals("India") && b2.equals("Australia")){
           double c = Double.parseDouble(jTextField1.getText());
           double k = (double)(c*0.01876);
           jTextField2.setText(String.valueOf(k));
       }
           if(b1.equals("India") && b2.equals("France")){
           double c = Double.parseDouble(jTextField1.getText());
           double k = (double)(c*0.01116);
           jTextField2.setText(String.valueOf(k));
       }  
           
           
                      
         //        ****Indonesia****   
           
           if(b1.equals("Indonesia") && b2.equals("Brazil")){
           double c = Double.parseDouble(jTextField1.getText());
           double k = (double)(c*0.00032);
           jTextField2.setText(String.valueOf(k));
           
       }
       
       if(b1.equals("Indonesia") && b2.equals("Canada")){
           double c = Double.parseDouble(jTextField1.getText());
           double k = (double)(c*0.000089);
           jTextField2.setText(String.valueOf(k));
           
       }
       if(b1.equals("Indonesia") && b2.equals("India")){
           double c = Double.parseDouble(jTextField1.getText());
           double k = (double)(c*0.0054);
           jTextField2.setText(String.valueOf(k));
           
       }
        if(b1.equals("Indonesia") && b2.equals("Indonesia")){
           double c = Double.parseDouble(jTextField1.getText());
           jTextField2.setText(String.valueOf(c));
           
       }
         if(b1.equals("Indonesia") && b2.equals("Nigeria")){
           double c = Double.parseDouble(jTextField1.getText());
           double k = (double)(c*0.051);
           jTextField2.setText(String.valueOf(k));
           
       }
          if(b1.equals("Indonesia") && b2.equals("USA")){
           double c = Double.parseDouble(jTextField1.getText());
           double k = (double)(c*0.000066);
           jTextField2.setText(String.valueOf(k));   
       }
           if(b1.equals("Indonesia") && b2.equals("Kenya")){
           double c = Double.parseDouble(jTextField1.getText());
           double k = (double)(c*0.0096);
           jTextField2.setText(String.valueOf(k));
       }
           if(b1.equals("Indonesia") && b2.equals("Pakistan")){
           double c = Double.parseDouble(jTextField1.getText());
           double k = (double)(c*0.020);
           jTextField2.setText(String.valueOf(k));
       }
           if(b1.equals("Indonesia") && b2.equals("Australia")){
           double c = Double.parseDouble(jTextField1.getText());
           double k = (double)(c*0.00010);
           jTextField2.setText(String.valueOf(k));
       }
           if(b1.equals("Indonesia") && b2.equals("France")){
           double c = Double.parseDouble(jTextField1.getText());
           double k = (double)(c*0.000060);
           jTextField2.setText(String.valueOf(k));
       }
           
                              
         //        ****Nigeria****   
           
           if(b1.equals("Nigeria") && b2.equals("Brazil")){
           double c = Double.parseDouble(jTextField1.getText());
           double k = (double)(c*0.0062);
           jTextField2.setText(String.valueOf(k));
           
       }
       
       if(b1.equals("Nigeria") && b2.equals("Canada")){
           double c = Double.parseDouble(jTextField1.getText());
           double k = (double)(c*0.0017);
           jTextField2.setText(String.valueOf(k));
           
       }
       if(b1.equals("Nigeria") && b2.equals("India")){
           double c = Double.parseDouble(jTextField1.getText());
           double k = (double)(c*0.11);
           jTextField2.setText(String.valueOf(k));
           
       }
        if(b1.equals("Nigeria") && b2.equals("Indonesia")){
           double c = Double.parseDouble(jTextField1.getText());
           double k = (double)(c*19.52);
           jTextField2.setText(String.valueOf(k));
           
       }
         if(b1.equals("Nigeria") && b2.equals("Nigeria")){
           double c = Double.parseDouble(jTextField1.getText());
           jTextField2.setText(String.valueOf(c));
           
       }
          if(b1.equals("Nigeria") && b2.equals("USA")){
           double c = Double.parseDouble(jTextField1.getText());
           double k = (double)(c*0.0013);
           jTextField2.setText(String.valueOf(k));   
       }
           if(b1.equals("Nigeria") && b2.equals("Kenya")){
           double c = Double.parseDouble(jTextField1.getText());
           double k = (double)(c*0.19);
           jTextField2.setText(String.valueOf(k));
       }
           if(b1.equals("Nigeria") && b2.equals("Pakistan")){
           double c = Double.parseDouble(jTextField1.getText());
           double k = (double)(c*0.39);
           jTextField2.setText(String.valueOf(k));
       }
           if(b1.equals("Nigeria") && b2.equals("Australia")){
           double c = Double.parseDouble(jTextField1.getText());
           double k = (double)(c*0.0020);
           jTextField2.setText(String.valueOf(k));
       }
           if(b1.equals("Nigeria") && b2.equals("France")){
           double c = Double.parseDouble(jTextField1.getText());
           double k = (double)(c*0.0012);
           jTextField2.setText(String.valueOf(k));
       }   
           
           
                                         
         //        ****USA****   
           
           if(b1.equals("USA") && b2.equals("Brazil")){
           double c = Double.parseDouble(jTextField1.getText());
           double k = (double)(c*4.85);
           jTextField2.setText(String.valueOf(k));
           
       }
       
       if(b1.equals("USA") && b2.equals("Canada")){
           double c = Double.parseDouble(jTextField1.getText());
           double k = (double)(c*1.36);
           jTextField2.setText(String.valueOf(k));
           
       }
       if(b1.equals("USA") && b2.equals("India")){
           double c = Double.parseDouble(jTextField1.getText());
           double k = (double)(c*82.69);
           jTextField2.setText(String.valueOf(k));
           
       }
        if(b1.equals("USA") && b2.equals("Indonesia")){
           double c = Double.parseDouble(jTextField1.getText());
           double k = (double)(c*15202.55);
           jTextField2.setText(String.valueOf(k));
           
       }
         if(b1.equals("USA") && b2.equals("Nigeria")){
           double c = Double.parseDouble(jTextField1.getText());
           double k = (double)(c*778.75);
           jTextField2.setText(String.valueOf(c));
           
       }
          if(b1.equals("USA") && b2.equals("USA")){
           double c = Double.parseDouble(jTextField1.getText());
           jTextField2.setText(String.valueOf(c));   
       }
           if(b1.equals("USA") && b2.equals("Kenya")){
           double c = Double.parseDouble(jTextField1.getText());
           double k = (double)(c*145.45);
           jTextField2.setText(String.valueOf(k));
       }
           if(b1.equals("USA") && b2.equals("Pakistan")){
           double c = Double.parseDouble(jTextField1.getText());
           double k = (double)(c*304.70);
           jTextField2.setText(String.valueOf(k));
       }
           if(b1.equals("USA") && b2.equals("Australia")){
           double c = Double.parseDouble(jTextField1.getText());
           double k = (double)(c*1.54);
           jTextField2.setText(String.valueOf(k));
       }
           if(b1.equals("USA") && b2.equals("France")){
           double c = Double.parseDouble(jTextField1.getText());
           double k = (double)(c*0.92);
           jTextField2.setText(String.valueOf(k));
       }
           
           
                     
              //        ****Kenya****   
           
           if(b1.equals("Kenya") && b2.equals("Brazil")){
           double c = Double.parseDouble(jTextField1.getText());
           double k = (double)(c*0.033);
           jTextField2.setText(String.valueOf(k));
           
       }
       
       if(b1.equals("Kenya") && b2.equals("Canada")){
           double c = Double.parseDouble(jTextField1.getText());
           double k = (double)(c*0.0093);
           jTextField2.setText(String.valueOf(k));
           
       }
       if(b1.equals("Kenya") && b2.equals("India")){
           double c = Double.parseDouble(jTextField1.getText());
           double k = (double)(c*0.57);
           jTextField2.setText(String.valueOf(k));
           
       }
        if(b1.equals("Kenya") && b2.equals("Indonesia")){
           double c = Double.parseDouble(jTextField1.getText());
           double k = (double)(c*49.89);
           jTextField2.setText(String.valueOf(k));
           
       }
         if(b1.equals("Kenya") && b2.equals("Nigeria")){
           double c = Double.parseDouble(jTextField1.getText());
           double k = (double)(c*5.36);
           jTextField2.setText(String.valueOf(c));
           
       }
          if(b1.equals("Kenya") && b2.equals("USA")){
           double c = Double.parseDouble(jTextField1.getText());
           double k = (double)(c*0.0069);
           jTextField2.setText(String.valueOf(k));   
       }
           if(b1.equals("Kenya") && b2.equals("Kenya")){
           double c = Double.parseDouble(jTextField1.getText());
           jTextField2.setText(String.valueOf(c));
       }
           if(b1.equals("Kenya") && b2.equals("Pakistan")){
           double c = Double.parseDouble(jTextField1.getText());
           double k = (double)(c*2.10);
           jTextField2.setText(String.valueOf(k));
       }
           if(b1.equals("Kenya") && b2.equals("Australia")){
           double c = Double.parseDouble(jTextField1.getText());
           double k = (double)(c*0.011);
           jTextField2.setText(String.valueOf(k));
       }
           if(b1.equals("Kenya") && b2.equals("France")){
           double c = Double.parseDouble(jTextField1.getText());
           double k = (double)(c*0.0063);
           jTextField2.setText(String.valueOf(k));
       }
           
           
          
              //        ****Pakistan****   
           
           if(b1.equals("Pakistan") && b2.equals("Brazil")){
           double c = Double.parseDouble(jTextField1.getText());
           double k = (double)(c*0.016);
           jTextField2.setText(String.valueOf(k));
           
       }
       
       if(b1.equals("Pakistan") && b2.equals("Canada")){
           double c = Double.parseDouble(jTextField1.getText());
           double k = (double)(c*0.0045);
           jTextField2.setText(String.valueOf(k));
           
       }
       if(b1.equals("Pakistan") && b2.equals("India")){
           double c = Double.parseDouble(jTextField1.getText());
           double k = (double)(c*0.27);
           jTextField2.setText(String.valueOf(k));
           
       }
        if(b1.equals("Pakistan") && b2.equals("Indonesia")){
           double c = Double.parseDouble(jTextField1.getText());
           double k = (double)(c*49.89);
           jTextField2.setText(String.valueOf(k));
           
       }
         if(b1.equals("Pakistan") && b2.equals("Nigeria")){
           double c = Double.parseDouble(jTextField1.getText());
           double k = (double)(c*2.56);
           jTextField2.setText(String.valueOf(k));
           
       }
          if(b1.equals("Pakistan") && b2.equals("USA")){
           double c = Double.parseDouble(jTextField1.getText());
           double k = (double)(c*0.0033);
           jTextField2.setText(String.valueOf(c));   
       }
           if(b1.equals("Pakistan") && b2.equals("Kenya")){
           double c = Double.parseDouble(jTextField1.getText());
           double k = (double)(c*0.48);
           jTextField2.setText(String.valueOf(k));
       }
           if(b1.equals("Pakistan") && b2.equals("Pakistan")){
           double c = Double.parseDouble(jTextField1.getText());
           jTextField2.setText(String.valueOf(c));
       }
           if(b1.equals("Pakistan") && b2.equals("Australia")){
           double c = Double.parseDouble(jTextField1.getText());
           double k = (double)(c*0.0051);
           jTextField2.setText(String.valueOf(k));
       }
           if(b1.equals("Pakistan") && b2.equals("France")){
           double c = Double.parseDouble(jTextField1.getText());
           double k = (double)(c*0.0030);
           jTextField2.setText(String.valueOf(k));
       }
           
           
           //        ****Australia****   
           
           if(b1.equals("Australia") && b2.equals("Brazil")){
           double c = Double.parseDouble(jTextField1.getText());
           double k = (double)(c*3.14);
           jTextField2.setText(String.valueOf(k));
           
       }
       
       if(b1.equals("Australia") && b2.equals("Canada")){
           double c = Double.parseDouble(jTextField1.getText());
           double k = (double)(c*0.88);
           jTextField2.setText(String.valueOf(k));
           
       }
       if(b1.equals("Australia") && b2.equals("India")){
           double c = Double.parseDouble(jTextField1.getText());
           double k = (double)(c*53.54);
           jTextField2.setText(String.valueOf(k));
           
       }
        if(b1.equals("Australia") && b2.equals("Indonesia")){
           double c = Double.parseDouble(jTextField1.getText());
           double k = (double)(c*9841.96);
           jTextField2.setText(String.valueOf(k));
           
       }
         if(b1.equals("Australia") && b2.equals("Nigeria")){
           double c = Double.parseDouble(jTextField1.getText());
           double k = (double)(c*500.82);
           jTextField2.setText(String.valueOf(c));
           
       }
          if(b1.equals("Australia") && b2.equals("USA")){
           double c = Double.parseDouble(jTextField1.getText());
           double k = (double)(c*0.65);
           jTextField2.setText(String.valueOf(k));   
       }
           if(b1.equals("Australia") && b2.equals("Kenya")){
           double c = Double.parseDouble(jTextField1.getText());
           double k = (double)(c*94.17);
           jTextField2.setText(String.valueOf(k));
       }
           if(b1.equals("Australia") && b2.equals("Pakistan")){
           double c = Double.parseDouble(jTextField1.getText());
           double k = (double)(c*197.35);
           jTextField2.setText(String.valueOf(k));
       }
           if(b1.equals("Australia") && b2.equals("Australia")){
           double c = Double.parseDouble(jTextField1.getText());
           jTextField2.setText(String.valueOf(c));
       }
           if(b1.equals("Australia") && b2.equals("France")){
           double c = Double.parseDouble(jTextField1.getText());
           double k = (double)(c*0.59);
           jTextField2.setText(String.valueOf(k));
       }
          
                      
           //        ****France****   
           
           if(b1.equals("France") && b2.equals("Brazil")){
           double c = Double.parseDouble(jTextField1.getText());
           double k = (double)(c*5.29);
           jTextField2.setText(String.valueOf(k));
           
       }
       
       if(b1.equals("France") && b2.equals("Canada")){
           double c = Double.parseDouble(jTextField1.getText());
           double k = (double)(c*1.48);
           jTextField2.setText(String.valueOf(k));
           
       }
       if(b1.equals("France") && b2.equals("India")){
           double c = Double.parseDouble(jTextField1.getText());
           double k = (double)(c*90.03);
           jTextField2.setText(String.valueOf(k));
           
       }
        if(b1.equals("France") && b2.equals("Indonesia")){
           double c = Double.parseDouble(jTextField1.getText());
           double k = (double)(c*16545.85);
           jTextField2.setText(String.valueOf(k));
           
       }
         if(b1.equals("France") && b2.equals("Nigeria")){
           double c = Double.parseDouble(jTextField1.getText());
           double k = (double)(c*842.11);
           jTextField2.setText(String.valueOf(c));
           
       }
          if(b1.equals("France") && b2.equals("USA")){
           double c = Double.parseDouble(jTextField1.getText());
           double k = (double)(c*1.09);
           jTextField2.setText(String.valueOf(k));   
       }
           if(b1.equals("France") && b2.equals("Kenya")){
           double c = Double.parseDouble(jTextField1.getText());
           double k = (double)(c*158.35);
           jTextField2.setText(String.valueOf(k));
       }
           if(b1.equals("France") && b2.equals("Pakistan")){
           double c = Double.parseDouble(jTextField1.getText());
           double k = (double)(c*331.83);
           jTextField2.setText(String.valueOf(k));
       }
           if(b1.equals("France") && b2.equals("Australia")){
           double c = Double.parseDouble(jTextField1.getText());
           double k = (double)(c*1.68);
           jTextField2.setText(String.valueOf(k));
       }
           if(b1.equals("France") && b2.equals("France")){
           double c = Double.parseDouble(jTextField1.getText());
           jTextField2.setText(String.valueOf(c));
       }
           
           
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Converter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Converter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Converter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Converter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Converter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
